# Generated by Django 4.1.7 on 2023-04-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('nrTelCelular', models.CharField(blank=True, max_length=11, null=True, verbose_name='n° telefone celular')),
            ],
        ),
    ]
