# Generated by Django 4.1.7 on 2023-04-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='protocolo',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
