# Generated by Django 4.1.7 on 2023-04-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
