# Generated by Django 4.1.7 on 2023-04-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_email_alter_client_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nome',
            field=models.CharField(help_text='Somente o primeiro nome.', max_length=50),
        ),
    ]
